// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHcDxRpTmfBqlwDnh7w_63-ohNKsuoN8',
    appId: '1:791573636194:web:672fc0f33eb902fa281d3b',
    messagingSenderId: '791573636194',
    projectId: 'smart-market-place-c1827',
    authDomain: 'smart-market-place-c1827.firebaseapp.com',
    storageBucket: 'smart-market-place-c1827.firebasestorage.app',
    measurementId: 'G-P9ZT2VCHKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp6hsyWG-2Mf1p6M2jvZmv5-XZHYctW4o',
    appId: '1:791573636194:android:363390cb7e57a480281d3b',
    messagingSenderId: '791573636194',
    projectId: 'smart-market-place-c1827',
    storageBucket: 'smart-market-place-c1827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzQG1ORjTp_DdOPrmWlLxY4pl78LdoYCA',
    appId: '1:791573636194:ios:f2bcdf2d82383c82281d3b',
    messagingSenderId: '791573636194',
    projectId: 'smart-market-place-c1827',
    storageBucket: 'smart-market-place-c1827.firebasestorage.app',
    iosClientId: '791573636194-mu13tnt8sm9e4s2p90jjmrhoocrckmpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartServiceMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzQG1ORjTp_DdOPrmWlLxY4pl78LdoYCA',
    appId: '1:791573636194:ios:f2bcdf2d82383c82281d3b',
    messagingSenderId: '791573636194',
    projectId: 'smart-market-place-c1827',
    storageBucket: 'smart-market-place-c1827.firebasestorage.app',
    iosClientId: '791573636194-mu13tnt8sm9e4s2p90jjmrhoocrckmpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartServiceMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMHcDxRpTmfBqlwDnh7w_63-ohNKsuoN8',
    appId: '1:791573636194:web:4a539cc4ff97f8e0281d3b',
    messagingSenderId: '791573636194',
    projectId: 'smart-market-place-c1827',
    authDomain: 'smart-market-place-c1827.firebaseapp.com',
    storageBucket: 'smart-market-place-c1827.firebasestorage.app',
    measurementId: 'G-Z7JNGC0ZX8',
  );

}